First_milestone
camilevahviraki/Portfolio pull request #1
Opened 2022-03-17 11:13 UTC by camilevahviraki

### in this Milestone We :

**designed a Portfolio Home Page**
- added index.html file:
   Write the introduction of my background profile.
- added index.css file and:
  Design the HTML file and let it look good.
- edited the README.md file:
   Added description to my project.

2022-03-17 14:11 UTC, ShoiraTa requested changes
Hi @camilevahviraki ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 
I was not able to add comments directly in readme file, so I will list them here: 

- [ ] It would be nice to add more information in `Getting started` section to make it clear for others how to setup the project. 
Try this
```
 ## Getting Started

To get a local copy up and running follow these simple example steps.

- copy this link `https://github.com/camilevahviraki/Portfolio.git`.
- get the directory that you want to clone the repository.
- open the command prompt in this directory.
- write `git clone https://github.com/camilevahviraki/Portfolio.git`.
- go to the repository folder in your command prompt `cd Portfolio`
```

- [ ] `MIT` license link does not work, please consider adding MIT file fix this issue


_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 14:11 UTC, ShoiraTa commented on index.css
> +}
- [ ] Please try to match the design with the one provided in Figma, currently, the `navbar` has more padding than provided: 

Your design  | Figma design
------------- | -------------
<img width="436" alt="Screenshot 2022-03-17 at 17 45 35" src="https://user-images.githubusercontent.com/77038610/158822206-206ea539-b1e8-447d-bd51-a2b6d4e19341.png"> | <img width="440" alt="Screenshot 2022-03-17 at 17 45 17" src="https://user-images.githubusercontent.com/77038610/158822159-53f11cd5-23cd-468f-bbee-2a8d95179bc1.png">

- [ ] Please always try to avoid maying out the items on the page using margins and padding. Instead you can use `flexbox` and `grid`
- [ ] Please increase the size of the `hamburger` button as provided

2022-03-17 14:11 UTC, ShoiraTa commented on index.html
> +      </div>
- [ ] I recommend you to use semantic HTML, please wrap the `humburger` icon and logo into a `button` tag and take the logo out of the nav container.

```
  <nav> 
    <button>
     <img src="images/Menu.svg" alt="hamburger" />
    </button>
  </nav>
```

2022-03-17 14:11 UTC, ShoiraTa commented on index.html
> +      </div>
- [ ] `Camilux` is supposed to be a logo, and usually, logo is a link that takes users to the homepage. Please wrap `Camilux` with  an `<a> `tag

2022-03-17 14:11 UTC, ShoiraTa commented on index.html
> +          <img src="./images/medium.png" alt="" class="png_img" />
- [ ] All the social links should be wrapped with` <ul> <li>` tags, eg.:

```
<ul>
  <li>
<a href="#" >
    <img src="./images/LinkedinIcon.png" alt="" class="png_img" />
  </a>
  </li>
  <li>
    <a href="#" ><img src="./images/medium.png" alt="" class="png_img" /></a>
  </li>
</ul>
```

- [ ] The icons  seem to be broken, please check the icon files one more time:
<img width="427" alt="Screenshot 2022-03-17 at 17 53 13" src="https://user-images.githubusercontent.com/77038610/158823880-7e4e64a1-9e83-4920-81f5-7703799193e6.png">

2022-03-17 14:11 UTC, ShoiraTa commented on index.html
> +      <div>
- [ ] Within the requirements,  content of this section should be aligned with `flexbox`

2022-03-17 14:11 UTC, ShoiraTa commented on index.css
> +}
- [ ] In small mobile screens the `navbar` and the page are broken. This is happening because of the relative position of the hamburger button. Please consider using `flexbox` instead of setting relative position and fixed width 🙏🏻
<img width="345" alt="Screenshot 2022-03-17 at 18 01 20" src="https://user-images.githubusercontent.com/77038610/158825312-0ad56ef1-c937-424c-a1dd-f9d64947d21c.png">

2022-03-17 22:24 UTC, JuliCarracedo requested changes
Hi @camilevahviraki , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- [✔️](https://emojipedia.org/check-mark/) Professional repository
- [✔️](https://emojipedia.org/check-mark/) Great job applying the required changes!
- [✔️](https://emojipedia.org/check-mark/) Your resume looks stunning!

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] On smaller devices, there's still a gap to the right of your application. I tried finding the source of the bug, but I didn't find any obvious culprit. You can schedule a meeting with a senior TSE if you need help solving it.
![Review](https://user-images.githubusercontent.com/69858269/158903993-918122c9-5eb5-428a-9bbc-949340a64735.PNG)

## Optional suggestions

- [OPTIONAL] Usually PR titles must be descriptive and reflect what you are bringing into the project. Since the previous reviewer didn't point it out, this is optional, but it is part of the [general requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 08:47 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @camilevahviraki👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

## Optional suggestions
I am marking these changes as optional because they were missed by the previous reviewer, But I strongly suggest you consider them
- [ ]  Check the comments under the review.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 08:47 UTC, thecodechaser commented on index.html
> +    </nav>
- [ ] [optional]  Please place this entire section in `<header>`, This will make sure our code is semantic.

2022-03-18 08:47 UTC, thecodechaser commented on index.html
> +      <a href="#"><h2>Camilux</h2></a>
- [ ] [optional] Please remove the `<h2>` inside anchor tag, it's not a good practice to place headings inside anchor tag.

2022-03-18 08:56 UTC, merged